### ISSUE TITLE
customValidation file

### ISSUE THREAD

**Issue by samuelWilliams99** [FlatF-ish/flatfish-back-end#1]
This file implements support for custom validation functions
It should include:
- [x] Some local associative array for keeping track of functions
- [x] A registerValidationFunction(name, function) function will checks types, then adds to array
- [x] A callValidationFunction(name, val, userId) function that calls the validation func. This function should return a Promise, to allow validation functions to take some time. 
  - First lookup userId to check if they're part of a house, if so get the houseId
  - Call the valid func with val, userId and houseId
  - If valid function doesn't return a Promise:
    - If the value is a boolean, accept with {valid: \<isValid>, error: "Unknown"}   
( Only specify error if valid = false )
    - Else check the return is of the above type and accept that
  - Else, resolve in a .then()
    - Same behaviour as above

This function should always accept with {valid: \<isValid>, error: \<error or null if valid>}

**Comment by JoshuaR830** [comment]
Sounds like a job for Sam

**Comment by samuelWilliams99** [comment]
Written the code, will commit after merges

**Comment by samuelWilliams99** [comment]
Added into src/util
